exclude: 'build/'
minimum_pre_commit_version: 4.4.0
x-uv-dependency: &uv-dependency "uv==0.9.15"
default_language_version:
    python: python3.12

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-merge-conflict
        args: ['--assume-in-merge']
    -   id: trailing-whitespace
        exclude: '\.py$'
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: end-of-file-fixer
        exclude: '^(.*\.svg|.*\.md)$'
    -   id: no-commit-to-branch
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: detect-private-key
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-symlinks
    -   id: check-toml

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format

ci:
    autofix_commit_msg: '[pre-commit.ci] Auto format from pre-commit.com hooks'
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autofix_prs: true
    autoupdate_branch: ''
    autoupdate_schedule: weekly
    submodules: false
