name: Feature Request
description: Suggest a new feature or improvement.
labels: ["enhancement"]
body:
  - type: textarea
    id: problem-statement
    attributes:
      label: Problem statement / motivation
      description: Describe the problem or motivation behind this request.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: Describe the solution you would like to see.
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other information or context about the feature request.
    validations:
      required: false
